CREATE SCHEMA IF NOT EXISTS Redes2P2 ;
USE Redes2P2 ;

CREATE TABLE IF NOT EXISTS Redes2P2.Report(
  idReport INT NOT NULL AUTO_INCREMENT,
  carnet VARCHAR(200) NOT NULL,
  nombre VARCHAR(800) NOT NULL,
  curso VARCHAR(800) NOT NULL,
  servidor VARCHAR(200) NOT NULL,
  fecha VARCHAR(100) NOT NULL,
  cuerpo VARCHAR(800) NOT NULL,
  PRIMARY KEY (idReport));

