version: "3.5"

services:
  loadbalancer:
    build: ./nginx
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - api-201602625
      - api-201602986
      - api-201602870
      - api-199911132
    networks:
      - redes2net

  mongoservice:
    image : mongo:latest
    container_name: mongoservice  
    volumes:
      - ./mongo/database:/data/db
    ports:
      - 27017:27017
    restart: unless-stopped
    networks:
      - redes2net

  api-201602625:
    container_name: api-201602625
    build:
      context: ./API
      dockerfile: Dockerfile
      args:
        - API_PORT=3001
    ports:
     - 3001:3001
    links:
      - mongoservice
    restart: unless-stopped
    environment:
      - FIRMA=201602625
      - SERVER_HOSTNAME=0.0.0.0
      - SERVER_PORT=3001
      - MONGO_HOST=mongoservice
      - MONGO_PORT=27017
      - db_retry_time=2000
    networks:
      - redes2net

  api-201602986:
    container_name: api-201602986
    build:
      context: ./API
      dockerfile: Dockerfile
      args:
        - API_PORT=3002
    ports:
     - 3002:3002
    links:
      - mongoservice
    restart: unless-stopped
    environment:
      - FIRMA=201602986
      - SERVER_HOSTNAME=0.0.0.0
      - SERVER_PORT=3002
      - MONGO_HOST=mongoservice
      - MONGO_PORT=27017
      - db_retry_time=2000
    networks:
      - redes2net

  api-201602870:
    container_name: api-201602870
    build:
      context: ./API
      dockerfile: Dockerfile
      args:
        - API_PORT=3003
    ports:
     - 3003:3003
    links:
      - mongoservice
    restart: unless-stopped
    environment:
      - FIRMA=201602870
      - SERVER_HOSTNAME=0.0.0.0
      - SERVER_PORT=3003
      - MONGO_HOST=mongoservice
      - MONGO_PORT=27017
      - db_retry_time=2000
    networks:
      - redes2net

  api-199911132:
    container_name: api-199911132
    build:
      context: ./API
      dockerfile: Dockerfile
      args:
        - API_PORT=3004
    ports:
     - 3004:3004
    links:
      - mongoservice
    restart: unless-stopped
    environment:
      - FIRMA=199911132
      - SERVER_HOSTNAME=0.0.0.0
      - SERVER_PORT=3004
      - MONGO_HOST=mongoservice
      - MONGO_PORT=27017
      - db_retry_time=2000
    networks:
      - redes2net
  
networks:
  redes2net:
    driver: bridge
